[nginx-forbidden]
enabled = true
filter = nginx-forbidden
port = 2053,8443,8880
logpath = /var/log/compassvpn/nginx_access.log
          /var/log/compassvpn/nginx_error.log
maxretry = 3
findtime = 600
bantime = 86400 
